import Foundation
import Testing
@testable import Mercury

@Suite("Digest Template Store")
struct DigestTemplateStoreTests {
    @Test("Load built-in digest template from app bundle")
    func loadBuiltInTemplateFromBundle() throws {
        let store = DigestTemplateStore()
        let bundle = try mercuryAppBundle()
        try store.loadBuiltInTemplates(bundle: bundle, subdirectory: DigestTemplateStore.builtInSubdirectory)

        #expect(store.loadedTemplateIDs.contains("single-text"))
        #expect(store.loadedTemplateIDs.contains("single-markdown"))
        #expect(store.loadedTemplateIDs.contains("multiple-markdown"))
    }

    @Test("Load single-text template and render conditional note")
    func loadAndRenderSingleTextTemplate() throws {
        let store = DigestTemplateStore()
        try store.loadTemplates(from: templateDirectoryInRepository())

        let template = try store.template(id: "single-text")
        #expect(template.version == "v1")
        #expect(template.requiredPlaceholders == ["articleTitle", "articleURL"])
        #expect(template.optionalPlaceholders.contains("articleAuthor"))
        #expect(template.defaultParameters["noteText"] == "")

        let renderedWithoutNote = try template.render(
            context: DigestTemplateRenderContext(
                scalars: [
                    "articleTitle": "Mercury",
                    "articleAuthor": "Neo",
                    "articleURL": "https://example.com/article"
                ]
            )
        )
        #expect(renderedWithoutNote == "Mercury by Neo https://example.com/article")

        let renderedWithNote = try template.render(
            context: DigestTemplateRenderContext(
                scalars: [
                    "articleTitle": "Mercury",
                    "articleURL": "https://example.com/article",
                    "includeNote": "true",
                    "noteText": "Worth reading."
                ]
            )
        )
        #expect(renderedWithNote == "Mercury https://example.com/article Worth reading.")
    }

    @Test("Load single-markdown template and render summary and note sections")
    func loadAndRenderSingleMarkdownTemplate() throws {
        let store = DigestTemplateStore()
        try store.loadTemplates(from: templateDirectoryInRepository())

        let template = try store.template(id: "single-markdown")
        #expect(template.version == "v1")
        #expect(template.requiredPlaceholders.contains("digestTitle"))
        #expect(template.optionalPlaceholders.contains("includeSummary"))

        let rendered = try template.render(
            context: DigestTemplateRenderContext(
                scalars: [
                    "exportDateTimeISO8601": "2026-03-29T12:00:00Z",
                    "digestTitle": "Digest Title",
                    "fileSlug": "digest-title",
                    "articleTitle": "Mercury",
                    "articleAuthor": "Neo",
                    "articleURL": "https://example.com/article",
                    "includeSummary": "true",
                    "summaryTextBlockquote": "Line 1\n> Line 2",
                    "summaryTargetLanguage": "en",
                    "summaryDetailLevel": "medium",
                    "includeNote": "true",
                    "noteText": "My note",
                    "labelSource": "Source",
                    "labelAuthor": "Author",
                    "labelNote": "My Take",
                    "labelSummaryGeneratedByPrefix": "Generated by",
                    "labelSummaryGeneratedBySuffix": "in"
                ]
            )
        )

        #expect(rendered.contains("title = 'Digest Title'"))
        #expect(rendered.contains("**Source**: [Mercury](https://example.com/article)"))
        #expect(rendered.contains("> Line 1\n> Line 2"))
        #expect(rendered.contains("**My Take**: My note"))
    }

    @Test("Reject malformed digest template with missing required placeholder")
    func rejectMalformedDigestTemplate() throws {
        let directory = try makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let invalidTemplate = """
        id: digest.invalid
        version: v1
        requiredPlaceholders:
          - articleTitle
          - articleURL
        template: |
          {{articleTitle}}
        """
        let fileURL = directory.appendingPathComponent("digest.invalid.yaml")
        try invalidTemplate.write(to: fileURL, atomically: true, encoding: .utf8)

        let store = DigestTemplateStore()
        do {
            try store.loadTemplates(from: directory)
            Issue.record("Expected malformed digest template validation failure, but loading succeeded.")
        } catch let error as DigestTemplateError {
            guard case let .invalidTemplateFile(name, reason) = error else {
                Issue.record("Unexpected error kind: \(error.localizedDescription)")
                return
            }
            #expect(name == "digest.invalid.yaml")
            #expect(reason.contains("Required placeholder(s) not found"))
            #expect(reason.contains("articleURL"))
        }
    }

    private func templateDirectoryInRepository() throws -> URL {
        let testsDirectory = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
        let templateDirectory = testsDirectory
            .appendingPathComponent("../Mercury/Resources/Digest/Templates")
            .standardizedFileURL

        guard FileManager.default.fileExists(atPath: templateDirectory.path) else {
            throw TestError.templateDirectoryNotFound(templateDirectory.path)
        }
        return templateDirectory
    }

    private func makeTemporaryDirectory() throws -> URL {
        let url = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("mercury-digest-template-tests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func mercuryAppBundle() throws -> Bundle {
        if let bundle = Bundle.allBundles.first(where: { $0.bundleIdentifier == "net.paradigmx.Mercury" }) {
            return bundle
        }
        if let bundle = Bundle.allBundles.first(where: { $0.bundleURL.lastPathComponent == "Mercury.app" }) {
            return bundle
        }
        throw TestError.appBundleNotFound
    }
}

private enum TestError: Error {
    case templateDirectoryNotFound(String)
    case appBundleNotFound
}
